config:
  credentials_location: "app/config.json" # Folder max amount
  project_id: "ttsapi-259817"
  article_folder: "/Users/kevinhernandez/Documents/flask-voice/app/templates/index/articles/"
  static_directory: "templates/index"

  